version: '3.8'
services:
  bnn-a:
    build: .
    container_name: bnn-a
    command: python3 BNN_A.py
    restart: no
    volumes:
      - ./shared_output:/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - API_KEY=619f6b8993584e4fa1adbb7e1768365b
    
  bnn-b:
    build: .
    container_name: bnn-b
    command: python3 BNN_B.py
    restart: no
    volumes:
      - ./shared_output:/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - API_KEY=619f6b8993584e4fa1adbb7e1768365b

  sentimenttool:
    build: .
    container_name: sentiment-tool
    command: python3 sentimenttool.py
    restart: no
    volumes:
      - ./shared_output:/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - API_KEY=619f6b8993584e4fa1adbb7e1768365b

  logic:
    build: .
    container_name: logic
    command: python3 logic.py
    restart: on-failure
    volumes:
      - ./shared_output:/output